apiVersion: v1
kind: Service
metadata:
  labels:
    app: hive-metastore
  name: hive-metastore
spec:
  ports:
    - name: thrift
      port: 9083
  selector:
    app: hive-metastore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  labels:
    app: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      imagePullSecrets:
        - name: azurecr
      containers:
        - name: hive-metastore
          image: hive-metastore:0.1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -Xmx1G"
          ports:
            - containerPort: 9083
              name: thrift
